- name: Init tables in database
  shell: "node services/db"
  args:
    chdir: "{{ root_path_generic_erc721_smart_contract_project }}"
- name: Retrieve 'smart_contract_address'
  postgresql_query:
    login_host: "{{ db_host }}"
    db: "{{ db_database }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    port: "{{ db_port }}"
    query: "SELECT address FROM smart_contracts;"
  register: smart_contracts_address_query
- name: Set fact smart_contracts_address
  ansible.builtin.set_fact:
    smart_contracts_address: "{{ smart_contracts_address_query['query_result'][0]['address'] }}"
- name: Retrieve unrevealed token uri
  postgresql_query:
    login_host: "{{ db_host }}"
    db: "{{ db_database }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    port: "{{ db_port }}"
    query: "SELECT json_uri FROM unrevealed_tokens;"
  register: unrevealed_token_json_uri_query
- name: Set fact unrevealed_token_json_uri
  ansible.builtin.set_fact:
    unrevealed_token_json_uri: "{{ unrevealed_token_json_uri_query['query_result'][0]['json_uri'] }}"

- name: Retrieve 'vouchers' non revealed
  postgresql_query:
    login_host: "{{ db_host }}"
    db: "{{ db_database }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    port: "{{ db_port }}"
    query: "SELECT EXISTS(SELECT * FROM vouchers WHERE NOT is_revealed);"
  register: vouchers_non_revealed_is_empty_query
- name: Set fact vouchers_non_revealed_is_empty
  ansible.builtin.set_fact:
    vouchers_non_revealed_is_empty: "{{ not vouchers_non_revealed_is_empty_query['query_result'][0]['exists'] }}"
- name: Populate vouchers database non revealed
  command: "npx truffle exec --network={{blockchain_network}} --unrevealedJsonUri={{unrevealed_token_json_uri}} --isRevealed=false --signers={{smart_contract_mint_signer_accounts}} --signerIndex=0 --smartContractAddress={{smart_contracts_address}} --domainName='{{smart_contract_domain_name}}' --domainVersion={{smart_contract_domain_version}} scripts/stages/populateVouchersDB/populateVouchersDB.js"
  args:
    chdir: "{{ root_path_generic_erc721_smart_contract_project }}"
  when: (not smart_contract_reveal) and vouchers_non_revealed_is_empty

- name: Retrieve 'vouchers' is revealed
  postgresql_query:
    login_host: "{{ db_host }}"
    db: "{{ db_database }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    port: "{{ db_port }}"
    query: "SELECT EXISTS(SELECT * FROM vouchers WHERE is_revealed);"
  register: vouchers_is_revealed_is_empty_query
- name: Set fact vouchers_is_revealed_is_empty
  ansible.builtin.set_fact:
    vouchers_is_revealed_is_empty: "{{ not vouchers_is_revealed_is_empty_query['query_result'][0]['exists'] }}"
- name: Populate vouchers database revealed
  command: "npx truffle exec --network={{blockchain_network}} --isRevealed=true --signers={{smart_contract_mint_signer_accounts}} --signerIndex=0 --smartContractAddress={{smart_contracts_address}} --domainName='{{smart_contract_domain_name}}' --domainVersion={{smart_contract_domain_version}} scripts/stages/populateVouchersDB/populateVouchersDB.js"
  args:
    chdir: "{{ root_path_generic_erc721_smart_contract_project }}"
  when: smart_contract_reveal and vouchers_is_revealed_is_empty