# Copyright 2023 celadari. All rights reserved. MIT license.
---
- name: Deploy smart contract and provision database
  hosts: localhost
  gather_facts: yes
  connection: local
  vars:
    - env: dev
    - nft_path_to_images_dir: "./data/{{ env }}/tokens/images/"
    - nft_path_to_jsons_dir: "./data/{{ env }}/tokens/jsons/"
    - smart_contract_path_to_json: "./data/{{ env }}/smart_contract/attributes.json"
    - smart_contract_path_to_image: "./data/{{ env }}/smart_contract/image.jpeg"
    - unrevealed_token_path_to_json: "./data/{{ env }}/unrevealed_token/attributes.json"
    - unrevealed_token_path_to_image: "./data/{{ env }}/unrevealed_token/image.jpeg"
  vars_files:
    - "./vars/{{ env }}/vars.yml"
    - "./vars/{{ env }}/vault"
  environment:
    DB_HOST: "{{ db_host }}"
    DB_DATABASE: "{{ db_database }}"
    DB_USER: "{{ db_user }}"
    DB_PASSWORD: "{{ db_password }}"
    DB_PORT: "{{ db_port }}"
    DB_DIALECT: "postgres"
    NFT_STORAGE_API_KEY: "{{ nft_storage_api_key }}"
    SMART_CONTRACT_EXTERNAL_URL: "{{ smart_contract_external_url }}"
    SMART_CONTRACT_FEE_RECIPIENT_ADDRESS: "{{ smart_contract_fee_recipient_address }}"
    SMART_CONTRACT_TOKENS_NB: "{{ nb_tokens }}"
    BLOCKCHAIN_HOST: "{{ blockchain_host }}"
    BLOCKCHAIN_PORT: "{{ blockchain_port_outside_container }}"
    BLOCKCHAIN_NETWORK_ID: "{{ blockchain_network_id }}"
  pre_tasks:
    - name: Install python packages
      ansible.builtin.pip:
        name: "{{ item }}"
        state: present
      with_items:
        - psycopg2-binary
    - name: "Install nodejs packages"
      community.general.npm:
        path: "{{ playbook_dir }}/.."
  roles:
    - deploy
