# Copyright 2023 celadari. All rights reserved. MIT license.
---
- name: Pause smart contract
  hosts: localhost
  gather_facts: yes
  connection: local
  vars:
    - env: dev
    - pause_or_unpause: pause
  vars_files:
    - "./vars/{{ env }}/vars.yml"
    - "./vars/{{ env }}/vault"
  environment:
    BLOCKCHAIN_HOST: "{{ blockchain_host }}"
    BLOCKCHAIN_PORT: "{{ blockchain_port }}"
    BLOCKCHAIN_NETWORK_ID: "{{ blockchain_network_id }}"
    PROVIDER_MNEMONIC_PHRASE: "{{ smart_contract_pauser_key_mnemonic }}"
  roles:
    - pause_or_unpause_contract
