# Copyright 2023 celadari. All rights reserved. MIT license.
---
- name: Populate vouchers database
  hosts: localhost
  gather_facts: yes
  connection: local
  vars:
    - env: dev
  vars_files:
    - "./vars/{{ env }}/vars.yml"
    - "./vars/{{ env }}/vault"
  environment:
    BLOCKCHAIN_HOST: "{{ blockchain_host }}"
    BLOCKCHAIN_PORT: "{{ blockchain_port_outside_container }}"
    BLOCKCHAIN_NETWORK_ID: "{{ blockchain_network_id }}"
    PROVIDER_MNEMONIC_PHRASE: "{{ smart_contract_mint_signer_key_mnemonic }}"
    SMART_CONTRACT_TOKENS_NB: "{{ nb_tokens }}"
    DB_HOST: "{{ db_host }}"
    DB_DATABASE: "{{ db_database }}"
    DB_USER: "{{ db_user }}"
    DB_PASSWORD: "{{ db_password }}"
    DB_PORT: "{{ db_port }}"
    DB_DIALECT: "postgres"
  roles:
    - populate_vouchers_db